[package]
name = "substrate-simnode"
version = "0.1.0"
authors = ["Seun Lanlege <seun@polytope.capital>"]
edition = "2021"
publish = false

[workspace]
members = ["examples/standalone", "examples/parachain"]

[dependencies]
# client deps
sc-executor = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.13" }
sc-service = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.13" }
sc-informant = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.13" }
sc-network = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.13" }
sc-cli = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.13" }
sc-basic-authorship = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.13" }
sc-rpc = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.13" }
sc-tracing = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.13" }
sc-transaction-pool = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.13" }
grandpa = { package = "sc-finality-grandpa", git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.13" }
sp-finality-grandpa = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.13" }
sp-consensus-babe = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.13" }
sp-consensus-aura = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.13" }
sc-consensus-babe = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.13" }
sc-consensus = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.13" }
sc-transaction-pool-api = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.13" }
sc-client-api = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.13" }
sc-rpc-server = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.13" }
manual-seal = { package = "sc-consensus-manual-seal", git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.13" }

# primitive deps
sp-core = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.13" }
sp-blockchain = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.13" }
sp-block-builder = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.13" }
sp-api = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.13" }
sp-transaction-pool = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.13" }
sp-consensus = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.13" }
sp-runtime = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.13" }
sp-session = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.13" }
sp-offchain = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.13" }
sp-inherents = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.13" }
sp-keyring = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.13" }
sp-externalities = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.13" }
sp-state-machine = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.13" }
sp-wasm-interface = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.13" }
sp-runtime-interface = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.13" }

# pallets
frame-system = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.13" }

# parachain stuff
parachain-inherent = { package = "cumulus-primitives-parachain-inherent", git = "https://github.com/purestake/cumulus", branch = "moonbeam-polkadot-v0.9.13" }
parachain-system = { package = "cumulus-pallet-parachain-system", git = "https://github.com/purestake/cumulus", branch = "moonbeam-polkadot-v0.9.13" }
sproof-builder = { package = "cumulus-test-relay-sproof-builder", git = "https://github.com/purestake/cumulus", branch = "moonbeam-polkadot-v0.9.13" }
parachain-info = { git = "https://github.com/purestake/cumulus", branch = "moonbeam-polkadot-v0.9.13" }

# polkadot
polkadot-primitives = { git = "https://github.com/purestake/polkadot", branch = "moonbeam-polkadot-v0.9.13" }

# others
codec = { package = "parity-scale-codec", version = "2.0.0" }
log = "0.4.8"
futures = "0.3.16"
tokio = { version = "1.13", features = ["signal"] }

# Calling RPC
jsonrpc-core = "18.0"
num-traits = "0.2.14"

[features]
default = ["std"]
# This is here so that we can use the `runtime_interface` procedural macro
std = []
